os: linux
dist: xenial
language: python
python: 3.7
sudo: required
fast_finish: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - gdal-bin
      - geographiclib-tools
      - libfftw3-dev
      - libgdal-dev
      - libgeographic-dev
  homebrew:
    packages:
      # GDAL is already included on osx images
      - geographiclib
      - fftw

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        # Work in a virtual environment to avoid having to do
        # "pip3 install --user"
        python3 -m venv venv
        source venv/bin/activate
    fi
  - pip install -e .

script: pytest --cov=s2p --cov-report term-missing tests

jobs:
  include:
    - stage: packaging
      name: "Python sdist installation"
      install: skip
      script:
        - python setup.py sdist
        - pip install dist/*.tar.gz
    - stage: packaging
      name: "Docker build"
      addons: skip
      install: skip
      script: docker build .

    - stage: test
    - stage: test
      python: 2.7
    - stage: test
      os: osx
      # The default osx image (xcode9.4 as of 2019-09-30) has a very old brew,
      # which crashes with the `addons` feature, so we use a non-default more recent one
      # (see https://github.com/Homebrew/homebrew-bundle/issues/540#issuecomment-518301382)
      osx_image: xcode10.2
      language: generic

    - stage: deploy
      if: tag IS present AND repo = glostis/s2p
      install: skip
      script: skip
      deploy:
        - provider: pypi
          user: glostis
          password:
            secure: "bv4+0sydGSp1ghppmOExXa+X2u3KymOjCF95OxN1g+h7yASUdsZlhHTjiBIicIfohG9PxKmFloSWgQCC17LFyP919ErFOqGSRTqekqelT6yPch4xuDZMiF5F4zFO51omGZ1rMTIFgWFvQgfBVF7mnXopz6FbsiC5kXoRMwLegYnrKgd+NF/xXPz/y/GKj/9HihALbmHZ47R+b4cX7zk8/2NezLOI27t2jMAMxF+90+XlvwuphHdKFgE2fkJ/0veeADlOXkacQQ19llQlV2j7dNPYEQo+Rbq/NAPYY5D9rWQDpUlhuQ7z0dmuYAadE3Oo6VemEH93qI/EPk53xpxJAu1FKjtOirqmycBPA7rTh5c+Aahfo/Nbsavx+3OBSNEiSpMdiJghHW6A06Ak9Eid1Bx4hwhpJ22EqZ6XfB+xwtZlr/K9k7ea1+A1bcoMOzFMKSYHQe3GgtMdXl+ol8GmwFqWBLaIULVu9rE31eLP/DQigsj7zx5Mrfc1ngzp3le9HGwaL4E2r7vvSeyuaEftePuOgRaXddAPk9riENYA5UBeqSrJZHJOPDxZZ4AZpB+DHeWBLSskNgSvLudUxLddyIBpqtcNAP1ACgmlEYsiNv6wdZkAYFOYfilQZ8ROWtGPPPRir0SBGs0zPnzZutX2Z1qK7xDGeJZaODc+nIh2+gY="
          server: https://test.pypi.org/legacy/
          distributions: sdist
          on:
            tags: true
